version: '3'
services:
  api:
    image: registry.gitlab.com/rrrtcdish2/biztoi_api_java/master:latest
    environment:
        SPRING_PROFILES_ACTIVE: 'prod'
        SPRING_DATASOURCE_URL: 'jdbc:postgresql://ec2-3-213-192-58.compute-1.amazonaws.com:5432/dakc80irsitdn7'
        SPRING_DATASOURCE_USERNAME: 'nuvkalnteozjei'
        SPRING_DATASOURCE_PASSWORD: '310e9b44e58545ebc10e907eac269615276e0b239a4ff4b40e3410eafb3a70d8'
        DRIVER_CLASS_NAME: 'org.postgresql.Driver'
        SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_BIZTOI_PROVIDER: 'cognito'
        SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_BIZTOI_CLIENT_NAME: 'biztoi'
        SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_BIZTOI_CLIENT_ID: '7o2r51udt31kp738eumcvkj7eg'
        SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_BIZTOI_CLIENT_SECRET: '1674uobc1lvpio2v8n9qvifecljiimce9dga7drf9amrq55i8bs4'
        SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_BIZTOI_SCOPE: 'openid, email, profile, aws.cognito.signin.user.admin'
        SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_BIZTOI_REDIRECT_URI: 'http://localhost:8000/login/oauth2/code/cognito'
        SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_BIZTOI_AUTHORIZATION_GRANT_TYPE: 'authorization_code'
        SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_COGNITO_AUTHORIZATION_URI: 'https://biztoi-app-dev.auth.ap-northeast-1.amazoncognito.com/oauth2/authorize'
        SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_COGNITO_TOKEN_URI: 'https://biztoi-app-dev.auth.ap-northeast-1.amazoncognito.com/oauth2/token'
        SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_COGNITO_USER_INFO_URI: 'https://biztoi-app-dev.auth.ap-northeast-1.amazoncognito.com/oauth2/userInfo'
        SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_COGNITO_JWK_SET_URI: 'https://cognito-idp.ap-northeast-1.amazonaws.com/ap-northeast-1_ccxqYNJs0/.well-known/jwks.json'
        SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_COGNITO_USER_NAME_ATTRIBUTE: 'username'
        SPRING_SESSION_TIMEOUT: 1H
        SERVER_PORT: 8000
        APPLICATION_FRONT_URL: 'https://biztoi.com'
        APPLICATION_RAKUTEN_APP_ID: '1026533309523038241'
        APPLICATION_RAKUTEN_GENRE_ID: '001006'
        APPLICATION_RAKUTEN_AFF_ID: '1a4c4098.1308e707.1a4c4099.4c2137b0'
        APPLICATION_AWS_ACCESSKEY: 'AKIAY5VJ52Y6JCAQASWB'
        APPLICATION_AWS_SECRETKEY: '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'
        APPLICATION_AWS_POOL: 'ap-northeast-1_WeZCIL5ti'
        LOGGING_LEVEL_ROOT: INFO
        LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY: INFO
    ports:
      - 8000:8000